title: Site


tabs:

  content:
    label: Content
    icon: text

    columns:
      - width: 3/4
        sections:

          - headline: Veröffentlicht
            type: pages
            status: listed
            info: " {{ page.moduleDisplayName}}"

          - headline: Ungelistet
            type: pages
            status: unlisted
            info: " {{ page.moduleDisplayName}}"

          - headline: Entwürfe
            type: pages
            status: draft
            info: " {{ page.moduleDisplayName}}"

      - width: 1/4
        sections:
          sidebar:
            type: matomo-sidebar
            link: false


  seo:
    label: SEO
    icon: search
    fields:

      seoTitle:
        label: SEO Title
        type: text

      seoDescription:
        label: SEO Description
        type: text
        validate:
          maxLength: 255

      author:
        label: Author
        type:  text

      keywords:
        label: Keywords
        type:  tags

      copyright:
        label: Copyright
        type:  textarea

      footerLinks:
        label: Links
        type:  textarea

  matomo:
    label: Besucherstatistik
    icon: clock
    columns:
      - width: 3/4
        sections:
          main:
            type: matomo-main
            defaults:
              limit: 8
              period: month
      - width: 1/4
        sections:
          sidebar:
            type: matomo-sidebar
            link: false
